import "./globals.css"
import NavBar from "../components/Ui/NavBar/NavBar"
import { ToastContainer } from "react-toastify"
import { cookies } from "next/headers"
import { decrypt } from "../lib/session"
import Providers from "@/providers/Providers"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <NavBar />
          <div className="pt-[90px]">{children}</div>
          <ToastContainer theme="dark" position="bottom-right" />
        </Providers>
      </body>
    </html>
  )
}
