import "./globals.css"
import NavBar from "@/components/NavBar/NavBar"
import { ToastContainer } from "react-toastify"
import { cookies } from "next/headers"
import { decrypt } from "../lib/session"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const cookieStore = await cookies()
  const token = cookieStore.get("session")?.value || null
  const session = token ? await decrypt(token) : null

  return (
    <html lang="en">
      <body className="antialiased">
        <NavBar session={session} />
        <div className="pt-[90px]">{children}</div>
        <ToastContainer theme="dark" />
      </body>
    </html>
  )
}
